site_name: Mòdul 0484 - Bases de dades
site_description: Publicació progressiva des d'un sol repositori
site_url: https://jpardo20.github.io/0484-bases-de-dades-23/

nav:
  - Inici: index.md
  - Continguts: continguts.md
  - Presentacions: https://jpardo20.github.io/0484-bases-de-dades-23/presentacions/

theme:
  name: material
  language: ca
  features:
    - navigation.indexes
    - navigation.sections
    - navigation.instant
    - navigation.tracking
    - content.code.copy

extra_css:
  - assets/styles.css

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - tables
  - toc:
      permalink: true
